import type { IGOTCourse } from '../../../src/types';

export const MOCK_IGOT_COURSES: IGOTCourse[] = [
  {
    id: 'igot-py-101',
    title: 'Python for Official Statistical Analysis & Data Processing',
    provider: 'iGOT Karmayogi / MoSPI Training Cell',
    duration: '2h 30m',
    competency: 'Python',
    competencyLevel: 3,
    category: 'Technical Competencies',
    difficulty: 'Intermediate',
    relevanceScore: 94,
    recommendationReason: 'Targeted to close Application Gap in pandas, NumPy and data cleaning for Survey rounds.',
    rating: 4.8,
    enrolledCount: 1420,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Python+Statistical+Analysis',
    isDemoData: true,
  },
  {
    id: 'igot-py-002',
    title: 'Fundamentals of Python Scripting for Civil Servants',
    provider: 'DoPT / Capacity Building Commission',
    duration: '1h 45m',
    competency: 'Python',
    competencyLevel: 2,
    category: 'Technical Competencies',
    difficulty: 'Beginner',
    relevanceScore: 82,
    recommendationReason: 'Foundational syntax and automation of routine spreadsheet workflows.',
    rating: 4.6,
    enrolledCount: 3840,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Python+Civil+Services',
    isDemoData: true,
  },
  {
    id: 'igot-vis-201',
    title: 'Data Visualization & Dashboarding for Government Statistics',
    provider: 'National Informatics Centre (NIC) & MoSPI',
    duration: '3h 15m',
    competency: 'Data Visualization',
    competencyLevel: 3,
    category: 'Technical Competencies',
    difficulty: 'Intermediate',
    relevanceScore: 92,
    recommendationReason: 'Your role requires L4 Data Visualization. Covers PowerBI, Matplotlib & official dissemination charts.',
    rating: 4.9,
    enrolledCount: 2150,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Data+Visualization+Statistics',
    isDemoData: true,
  },
  {
    id: 'igot-sur-301',
    title: 'Socio-Economic Survey Design & Quality Audit Protocols',
    provider: 'NSSO Division / NSSTA Faculty',
    duration: '4h 00m',
    competency: 'Survey Methodology',
    competencyLevel: 4,
    category: 'Statistical Competencies',
    difficulty: 'Advanced',
    relevanceScore: 89,
    recommendationReason: 'Advanced sampling frames, non-sampling error reduction, and CAPI validation checks.',
    rating: 4.7,
    enrolledCount: 980,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Survey+Design+Methodology',
    isDemoData: true,
  },
  {
    id: 'igot-sdg-101',
    title: 'National Indicator Framework for Sustainable Development Goals (SDGs)',
    provider: 'MoSPI SSD Division',
    duration: '2h 00m',
    competency: 'SDG Indicators',
    competencyLevel: 3,
    category: 'Statistical Competencies',
    difficulty: 'Intermediate',
    relevanceScore: 88,
    recommendationReason: 'Essential metadata compilation standards for State & National indicator monitoring.',
    rating: 4.8,
    enrolledCount: 1670,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Sustainable+Development+Goals+SDG',
    isDemoData: true,
  },
  {
    id: 'igot-aiml-101',
    title: 'Introduction to Artificial Intelligence in Public Governance',
    provider: 'National e-Governance Division (NeGD)',
    duration: '2h 15m',
    competency: 'AI / ML',
    competencyLevel: 2,
    category: 'Technical Competencies',
    difficulty: 'Beginner',
    relevanceScore: 90,
    recommendationReason: 'Emerging technology priority for official automated data imputation and anomaly detection.',
    rating: 4.5,
    enrolledCount: 4200,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Artificial+Intelligence+Governance',
    isDemoData: true,
  },
  {
    id: 'igot-cpi-201',
    title: 'Price Statistics: Consumer Price Index (CPI) Compilation & Hedonics',
    provider: 'Economic Statistics Division, MoSPI',
    duration: '3h 30m',
    competency: 'Price Statistics',
    competencyLevel: 3,
    category: 'Statistical Competencies',
    difficulty: 'Intermediate',
    relevanceScore: 85,
    recommendationReason: 'Covers price quotations validation, base year revisions, and weighting schemes.',
    rating: 4.7,
    enrolledCount: 840,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Consumer+Price+Index+Statistics',
    isDemoData: true,
  },
  {
    id: 'igot-sec-101',
    title: 'Cybersecurity, DPDP Act & Data Privacy for Statistical Databases',
    provider: 'Cert-In & Ministry of Electronics and IT',
    duration: '1h 30m',
    competency: 'Cybersecurity',
    competencyLevel: 3,
    category: 'Digital Governance',
    difficulty: 'Intermediate',
    relevanceScore: 87,
    recommendationReason: 'Mandatory compliance for handling microdata and anonymization standards under DPDP.',
    rating: 4.6,
    enrolledCount: 5120,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Cybersecurity+Data+Privacy+DPDP',
    isDemoData: true,
  },
];
