import { QuizAssessment } from '../types';

export const CLIENT_ASSESSMENTS: QuizAssessment[] = [
  {
    id: 'assess-py-l3',
    title: 'Python for Survey Microdata & Imputation Assessment',
    description: '10-minute diagnostic quiz assessing pandas dataframes, outlier detection, and stratum weights calculations.',
    competency: 'Python',
    timeLimitMinutes: 10,
    passingScore: 70,
    questions: [
      {
        id: 'py-q1',
        question: 'In survey data processing with Python pandas, which method correctly replaces missing income observations with the stratum median value?',
        options: [
          "df.groupby('stratum')['income'].transform(lambda x: x.fillna(x.median()))",
          "df['income'].fillna(df['income'].mean(), inplace=False)",
          "df.dropna(subset=['income'])",
          "df.replace('NaN', 0)",
        ],
        correctAnswer: 0,
        explanation: 'Using groupby with transform calculates the median within each stratum subgroup without reducing DataFrame rows.',
        difficulty: 'Medium',
        competency: 'Python',
        topic: 'pandas Imputation',
        sourceReference: 'MoSPI Statistical Data Processing Guidelines',
      },
      {
        id: 'py-q2',
        question: 'When calibrating multiplier weights in a stratified two-stage sample, which NumPy check validates that the inflated sample matches total population projection?',
        options: [
          'np.isclose(np.sum(sample_weights), projected_population, rtol=1e-4)',
          'np.equal_matrices(sample_weights, projected_population)',
          'np.count_nonzero(sample_weights)',
          'np.check_census_alignment(sample_weights)',
        ],
        correctAnswer: 0,
        explanation: 'np.isclose allows numerical floating point tolerance validation when checking sample weighting sums against census projections.',
        difficulty: 'Hard',
        competency: 'Python',
        topic: 'Weight Verification',
        sourceReference: 'NSSO Sampling Estimation Manual',
      },
      {
        id: 'py-q3',
        question: 'What is the primary computational benefit of utilizing vectorized operations in pandas over Python for-loops when processing millions of census records?',
        options: [
          'Vectorized operations execute in compiled C routines using SIMD parallel CPU instructions',
          'Vectorized operations automatically eliminate missing values without warnings',
          'Vectorized code bypasses operating system memory safety locks',
          'Loops in Python consume zero RAM memory',
        ],
        correctAnswer: 0,
        explanation: 'pandas and NumPy vectorization delegates operations to optimized C/Fortran routines with SIMD instruction sets, delivering 50x-100x speedups.',
        difficulty: 'Medium',
        competency: 'Python',
        topic: 'Performance & Vectorization',
        sourceReference: 'Python High-Performance Statistical Handbook',
      },
      {
        id: 'py-q4',
        question: 'Which pandas function is most effective for reshaping high-frequency industrial price quotations from long format into wide cross-tabulation by commodity code?',
        options: [
          "df.pivot_table(index='month', columns='item_code', values='price', aggfunc='mean')",
          "df.concat(['month', 'item_code'])",
          'df.melt(id_vars="item_code")',
          'df.sort_values(by="price")',
        ],
        correctAnswer: 0,
        explanation: 'pivot_table aggregates duplicate quotations and reshapes long time series records into matrix format for index compilation.',
        difficulty: 'Medium',
        competency: 'Python',
        topic: 'Data Reshaping',
        sourceReference: 'Price Statistics Division MoSPI',
      },
    ],
  },
  {
    id: 'assess-py-l4',
    title: 'Advanced Python for Official Statistics & Complex Survey Pipelines (Level 4)',
    description: 'Level 4 master validation covering out-of-core computing (Dask/Polars), multi-stage Taylor linearisation variance estimation, and statistical disclosure control (SDC).',
    competency: 'Python',
    timeLimitMinutes: 15,
    passingScore: 70,
    questions: [
      {
        id: 'py-l4-q1',
        question: 'When processing large microdata datasets (exceeding memory RAM) in Python, which approach ensures out-of-core chunked processing without memory exhaustion?',
        options: [
          'Using Polars lazy execution or Dask DataFrame computation graphs with delayed task chunks',
          'Loading the complete 50GB CSV file directly using standard pd.read_csv() into a single variable',
          'Disabling the operating system virtual swap space',
          'Converting all numeric columns into nested string arrays',
        ],
        correctAnswer: 0,
        explanation: 'Dask and Polars lazy dataframes partition computation into directed acyclic graphs (DAGs) and stream chunked batches through CPU cores without exhausting system memory.',
        difficulty: 'Hard',
        competency: 'Python',
        topic: 'Out-of-Core Processing',
        sourceReference: 'MoSPI Big Data & Computational Statistics Standard',
      },
      {
        id: 'py-l4-q2',
        question: 'In complex survey data analysis in Python, how is the Taylor series linearisation variance estimated for non-linear domain estimators (like poverty headcounts or Gini ratios)?',
        options: [
          'By linearising the non-linear estimator via first-order partial derivatives and computing the variance of the linearised surrogate across primary sampling units (PSUs)',
          'By calculating the simple standard deviation of the raw sample assuming i.i.d. random sampling',
          'By multiplying the sample mean by the number of survey rounds',
          'By deleting all outlier weights without variance calculations',
        ],
        correctAnswer: 0,
        explanation: 'Taylor series linearisation approximates non-linear statistics with linear functions of sample totals, allowing standard cluster-stratum variance formulas to be applied.',
        difficulty: 'Hard',
        competency: 'Python',
        topic: 'Complex Survey Variance Estimation',
        sourceReference: 'UN-NQAF Survey Sampling Variance Guidelines',
      },
      {
        id: 'py-l4-q3',
        question: 'Which Statistical Disclosure Control (SDC) algorithm in Python protects public use microdata (PUM) against re-identification risk while preserving marginal tabulation totals?',
        options: [
          'Targeted record swapping with k-anonymity checks and micro-aggregation of continuous expenditure variables',
          'Replacing all numeric columns with random integers',
          'Multiplying all observations by a fixed constant factor of 100',
          'Encrypting the dataset with AES-256 and deleting the decryption key',
        ],
        correctAnswer: 0,
        explanation: 'Standard SDC protocols apply k-anonymity, l-diversity, and microaggregation / record swapping to prevent indirect identification of respondents.',
        difficulty: 'Hard',
        competency: 'Python',
        topic: 'Statistical Disclosure Control (SDC)',
        sourceReference: 'MoSPI Microdata Dissemination & Privacy Policy',
      },
      {
        id: 'py-l4-q4',
        question: 'In automated statistical pipelines, how should Python decorators be applied to profile execution bottlenecks across survey imputation modules?',
        options: [
          'Using functools.wraps with cProfile / time.perf_counter to log execution latency and memory allocation per stratum function',
          'Writing custom print statements after every single line of code',
          'Rerunning the entire pipeline 500 times in a synchronous loop',
          'Suppressing all Python warning messages and tracebacks',
        ],
        correctAnswer: 0,
        explanation: 'Using function decorators with cProfile and perf_counter allows modular, non-intrusive latency and memory profiling across enterprise survey pipelines.',
        difficulty: 'Medium',
        competency: 'Python',
        topic: 'Pipeline Profiling & Performance',
        sourceReference: 'Python High-Performance Statistical Handbook',
      },
    ],
  },
  {
    id: 'assess-national-accounts',
    title: 'National Accounts (SNA 2008) & GVA Deflators Diagnostic',
    description: 'Specialized assessment evaluating Supply-Use Tables (SUT), informal sector estimation, and FISIM calculation.',
    competency: 'National Accounts (SNA 2008)',
    timeLimitMinutes: 12,
    passingScore: 70,
    questions: [
      {
        id: 'na-q1',
        question: 'Under SNA 2008 recommendations, how should Financial Intermediation Services Indirectly Measured (FISIM) be allocated between sectors?',
        options: [
          'Allocated as intermediate consumption of user industries and final consumption of households/government based on loan/deposit balances',
          'Treated solely as a deduction from nominal Gross Domestic Product at factor cost',
          'Ignored in national accounting since financial services have no physical output',
          'Added completely to household disposable income without industry breakdown',
        ],
        correctAnswer: 0,
        explanation: 'SNA 2008 requires FISIM to be allocated to intermediate consumption of user industries and final consumption of households based on reference interest rates.',
        difficulty: 'Hard',
        competency: 'National Accounts (SNA 2008)',
        topic: 'FISIM Accounting',
        sourceReference: 'UN System of National Accounts 2008, Chapter 6',
      },
      {
        id: 'na-q2',
        question: 'In the compilation of Supply and Use Tables (SUT), what identity must hold for every commodity group at purchasers’ prices?',
        options: [
          'Total Domestic Output + Imports + Trade/Transport Margins + Net Taxes on Products = Intermediate Consumption + Final Use + Exports',
          'Total Gross Output = Total Value Added + Subsidies',
          'Gross Value Added = Total Exports - Total Imports',
          'Domestic Output = Total Net Capital Formation',
        ],
        correctAnswer: 0,
        explanation: 'The fundamental commodity balance in SUT requires total supply at purchasers prices to equal total use at purchasers prices across all product groups.',
        difficulty: 'Medium',
        competency: 'National Accounts (SNA 2008)',
        topic: 'Supply-Use Balancing',
        sourceReference: 'CSO National Accounts Compilation Manual',
      },
      {
        id: 'na-q3',
        question: 'When deflating nominal Gross Value Added (GVA) in manufacturing using the Double Deflation method, which deflators are applied?',
        options: [
          'Gross output is deflated by product output price index; intermediate inputs are deflated by input cost price index',
          'Gross output and intermediate inputs are both deflated only by the Headline Consumer Price Index (CPI)',
          'GVA is deflated directly by the GDP deflator without considering input costs',
          'Double deflation implies multiplying nominal output by the exchange rate',
        ],
        correctAnswer: 0,
        explanation: 'Double deflation separately deflates gross output by an appropriate output price index and intermediate consumption by an input price index.',
        difficulty: 'Hard',
        competency: 'National Accounts (SNA 2008)',
        topic: 'Double Deflation',
        sourceReference: 'National Accounts Division (NAD) MoSPI',
      },
    ],
  },
  {
    id: 'assess-survey-sampling',
    title: 'Survey Sampling Design & Field Multipliers Diagnostic',
    description: 'Assessment covering probability proportional to size (PPS), CAPI validation rules, and multiplier weighting.',
    competency: 'Survey Methodology',
    timeLimitMinutes: 12,
    passingScore: 70,
    questions: [
      {
        id: 'ss-q1',
        question: 'In a stratified two-stage sampling design for NSSO household surveys, what is the formula for the design multiplier weight for household j in stratum h, FSU i?',
        options: [
          'w_hij = (1 / P_hi) * (H_hi / h_hi), where P_hi is FSU selection probability and H_hi/h_hi is second-stage sampling fraction',
          'w_hij = Total Population / Total Sample Size',
          'w_hij = Stratum Variance / Sample Mean',
          'w_hij = Total Enumerators / Total Villages',
        ],
        correctAnswer: 0,
        explanation: 'The design weight is the inverse of the inclusion probability: (1 / P_hi) * (H_hi / h_hi).',
        difficulty: 'Hard',
        competency: 'Survey Methodology',
        topic: 'Multiplier Calibration',
        sourceReference: 'NSSO Sampling Design Handbook',
      },
      {
        id: 'ss-q2',
        question: 'What is the primary advantage of selecting First Stage Units (FSUs) with Probability Proportional to Size (PPS) rather than Simple Random Sampling (SRS)?',
        options: [
          'Substantially reduces sampling variance for aggregate estimates when larger units account for larger shares of survey variables',
          'Guarantees zero non-response error during field fieldwork',
          'Eliminates the requirement of maintaining an urban frame survey (UFS)',
          'Allows field investigators to skip household listing',
        ],
        correctAnswer: 0,
        explanation: 'PPS sampling assigns higher selection probabilities to larger clusters, leading to higher estimation precision and lower design effects.',
        difficulty: 'Medium',
        competency: 'Survey Methodology',
        topic: 'PPS Sampling',
        sourceReference: 'SDRD Survey Design Manual',
      },
      {
        id: 'ss-q3',
        question: 'During Computer Assisted Personal Interviewing (CAPI), which real-time logical check prevents inconsistent demographic reporting in household rosters?',
        options: [
          'Hard range check enforcing: Age of child <= (Age of mother - 15)',
          'Automated battery level monitoring on tablets',
          'GPS coordinate logging without timestamp',
          'Text capitalization script',
        ],
        correctAnswer: 0,
        explanation: 'Hard logical validation rules in CAPI software (like CSPro / Survey Solutions) prevent biologically impossible household relationships from being entered in the field.',
        difficulty: 'Easy',
        competency: 'Survey Methodology',
        topic: 'CAPI Validation',
        sourceReference: 'FOD Field Operations Division Guidelines',
      },
    ],
  },
  {
    id: 'assess-price-statistics',
    title: 'Price Statistics, CPI Rebasing & Hedonic Indexing Diagnostic',
    description: 'Evaluates scanner data integration, hedonic quality adjustments, and geometric aggregations.',
    competency: 'Price Statistics',
    timeLimitMinutes: 10,
    passingScore: 70,
    questions: [
      {
        id: 'ps-q1',
        question: 'Why does the Jevons elementary price index formula prevent the upward elementary substitution bias associated with the Carli arithmetic mean?',
        options: [
          'Jevons uses an unweighted geometric mean of price relatives, which satisfies the time-reversal property',
          'Jevons adds fixed 5% tax subsidies to base period prices',
          'Jevons uses maximum prices observed across all retail markets',
          'Jevons ignores commodity quality shifts completely',
        ],
        correctAnswer: 0,
        explanation: 'The geometric mean formula (Jevons) satisfies time-reversal and circularity, eliminating the persistent upward drift of arithmetic averages.',
        difficulty: 'Hard',
        competency: 'Price Statistics',
        topic: 'Index Number Theory',
        sourceReference: 'Price Statistics Division MoSPI',
      },
      {
        id: 'ps-q2',
        question: 'When updating the Consumer Price Index (CPI) basket during base-year revisions, which data source provides the item weight weights?',
        options: [
          'Household Consumption Expenditure Survey (HCES) / CES microdata',
          'Stock exchange daily trading volumes',
          'Commercial bank interest rate schedules',
          'Customs import duty collections',
        ],
        correctAnswer: 0,
        explanation: 'The Consumer Expenditure Survey (CES/HCES) conducted by NSSO provides representative household expenditure shares for weighting items in the CPI basket.',
        difficulty: 'Medium',
        competency: 'Price Statistics',
        topic: 'CPI Weighting Base',
        sourceReference: 'National Statistical Office CPI Methodology',
      },
      {
        id: 'ps-q3',
        question: 'How does Hedonic Quality Adjustment prevent artificial inflation in technology and vehicle price indexes?',
        options: [
          'By estimating implicit characteristic prices via regression to isolate pure price changes from quality improvements',
          'By deleting technological products whenever specifications change',
          'By freezing electronic item prices for 10 years',
          'By rounding all prices to the nearest thousand rupees',
        ],
        correctAnswer: 0,
        explanation: 'Hedonic regression estimates the value of changed specifications (e.g. RAM, fuel efficiency), removing quality gains from reported inflation.',
        difficulty: 'Hard',
        competency: 'Price Statistics',
        topic: 'Hedonic Adjustments',
        sourceReference: 'MoSPI Price Statistics Technical Note',
      },
    ],
  },
];
