import { LearningCatalogueItem, UnifiedRecommendation } from '../types';

export const CLIENT_UNIFIED_CATALOGUE: LearningCatalogueItem[] = [
  // ==========================================
  // SOURCE 1: iGOT Karmayogi
  // ==========================================
  {
    id: 'cat-igot-py-101',
    title: 'Python for Official Statistical Analysis & Data Processing',
    source: 'iGOT Karmayogi',
    competency: 'Python',
    competencyLevel: 3,
    domain: 'Technical Competencies',
    difficulty: 'Intermediate',
    duration: '2h 30m',
    durationCategory: 'MEDIUM',
    prerequisites: 'Basic Python syntax and spreadsheet data manipulation',
    targetRole: 'Deputy Director (Statistics)',
    description: 'Comprehensive digital course on modern Python workflows in official statistics. Covers Pandas vector manipulation, NumPy arrays, survey microdata aggregation, and automated error imputation.',
    learningObjectives: [
      'Master Pandas DataFrame operations for multi-stage survey microdata',
      'Implement deterministic and donor-based imputation techniques',
      'Calculate weighted statistical aggregates across stratified survey rounds',
      'Automate monthly statistical table generation according to MoSPI standards',
    ],
    relevanceToGap: 'Targets identified Python application gap by elevating skills from foundational syntax (L2) to survey analysis pipelines (L3/L4).',
    expectedImprovement: 'Elevates Python Competency from Level 2 to Level 3 / Level 4 operational mastery.',
    isDemoData: true,
    datasetNotice: 'Development Dataset',
    rating: 4.8,
    enrolledCount: 1420,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Python+Statistical+Analysis',
    mode: 'Online Self-Paced (iGOT)',
    phase: 'FOUNDATION',
  },
  {
    id: 'cat-igot-py-002',
    title: 'Fundamentals of Python Scripting for Civil Servants',
    source: 'iGOT Karmayogi',
    competency: 'Python',
    competencyLevel: 2,
    domain: 'Technical Competencies',
    difficulty: 'Beginner',
    duration: '1h 45m',
    durationCategory: 'SHORT',
    prerequisites: 'Basic computer literacy and spreadsheet familiarity',
    targetRole: 'Junior Statistical Officer',
    description: 'Entry-level practical orientation to computational thinking and Python scripting for government administrative workflows and statistical automation.',
    learningObjectives: [
      'Understand core Python data types, lists, dictionaries, and loops',
      'Automate routine CSV and Excel report parsing',
      'Write reusable utility functions for administrative file handling',
    ],
    relevanceToGap: 'Prerequisite foundation for officers starting or consolidating basic scripting skills.',
    expectedImprovement: 'Establishes Level 2 syntax and procedural scripting baseline.',
    isDemoData: true,
    datasetNotice: 'Development Dataset',
    rating: 4.7,
    enrolledCount: 2310,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Python+Fundamentals',
    mode: 'Online Self-Paced (iGOT)',
    phase: 'FOUNDATION',
  },
  {
    id: 'cat-igot-na-201',
    title: 'National Accounts (SNA 2008) Framework & Supply-Use Tables',
    source: 'iGOT Karmayogi',
    competency: 'National Accounts (SNA 2008)',
    competencyLevel: 4,
    domain: 'Domain Competencies',
    difficulty: 'Advanced',
    duration: '4h 00m',
    durationCategory: 'MEDIUM',
    prerequisites: 'Basic macroeconomic accounting principles',
    targetRole: 'Joint Director (National Accounts)',
    description: 'Advanced macroeconomic accounting covering SNA 2008 standards, GVA double-deflation methodology, FISIM allocation, and informal sector estimation.',
    learningObjectives: [
      'Construct Supply and Use Tables (SUT) for multi-sectoral balancing',
      'Apply double-deflation techniques to measure real GVA',
      'Estimate informal economy contributions using enterprise survey multipliers',
    ],
    relevanceToGap: 'Bridges theoretical knowledge and practical balancing in national accounts estimation.',
    expectedImprovement: 'Elevates National Accounts competency to Level 4 analytical mastery.',
    isDemoData: true,
    datasetNotice: 'Development Dataset',
    rating: 4.9,
    enrolledCount: 890,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=National+Accounts+SNA+2008',
    mode: 'Online Self-Paced (iGOT)',
    phase: 'FOUNDATION',
  },
  {
    id: 'cat-igot-sm-301',
    title: 'Modern Survey Sampling Design & Multi-Stage Estimation',
    source: 'iGOT Karmayogi',
    competency: 'Survey Methodology',
    competencyLevel: 3,
    domain: 'Domain Competencies',
    difficulty: 'Intermediate',
    duration: '3h 15m',
    durationCategory: 'MEDIUM',
    prerequisites: 'Basic probability distributions and sampling concepts',
    targetRole: 'Assistant Director (Survey Design)',
    description: 'Practical training on stratified multi-stage cluster sampling, multiplier weight calculation, Urban Frame Survey (UFS) updates, and non-sampling error control.',
    learningObjectives: [
      'Design stratified two-stage sample frames for socio-economic surveys',
      'Calculate design weights and non-response calibration factors',
      'Validate CAPI routing rules and skip patterns in the field',
    ],
    relevanceToGap: 'Targets sampling methodology gaps in large-scale household and enterprise surveys.',
    expectedImprovement: 'Elevates Survey Methodology to Level 3/4 design certification.',
    isDemoData: true,
    datasetNotice: 'Development Dataset',
    rating: 4.8,
    enrolledCount: 1120,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Survey+Sampling+Design',
    mode: 'Online Self-Paced (iGOT)',
    phase: 'FOUNDATION',
  },
  {
    id: 'cat-igot-dp-401',
    title: 'Digital Personal Data Protection (DPDP) Act 2023 for Official Statisticians',
    source: 'iGOT Karmayogi',
    competency: 'Data Privacy & DPDP Act',
    competencyLevel: 3,
    domain: 'Digital Governance',
    difficulty: 'Intermediate',
    duration: '1h 30m',
    durationCategory: 'SHORT',
    prerequisites: 'None',
    targetRole: 'All Statistical Officers',
    description: 'Comprehensive compliance module on data fiduciaries, consent management, anonymization, and statistical disclosure control under the DPDP Act 2023.',
    learningObjectives: [
      'Understand statutory obligations of Data Fiduciaries in government',
      'Implement anonymization and pseudonymization protocols on microdata',
      'Ensure UN-FPOS compliance with statutory confidentiality mandates',
    ],
    relevanceToGap: 'Critical compliance requirement for microdata dissemination and public research access.',
    expectedImprovement: 'Establishes verified Level 3 legal and data privacy compliance.',
    isDemoData: true,
    datasetNotice: 'Development Dataset',
    rating: 4.9,
    enrolledCount: 3450,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=DPDP+Act+2023+Government',
    mode: 'Online Self-Paced (iGOT)',
    phase: 'FOUNDATION',
  },
  {
    id: 'cat-igot-dv-501',
    title: 'Official Statistical Visualizations & Dashboards for Policy Makers',
    source: 'iGOT Karmayogi',
    competency: 'Data Visualization',
    competencyLevel: 3,
    domain: 'Technical Competencies',
    difficulty: 'Intermediate',
    duration: '2h 00m',
    durationCategory: 'MEDIUM',
    prerequisites: 'Basic chart design and data summary skills',
    targetRole: 'Statistical Officer / Analyst',
    description: 'Best practices for translating complex statistical tables into intuitive dashboards, thematic heatmaps, and high-impact policy briefs using PowerBI, R Shiny, and Python Seaborn.',
    learningObjectives: [
      'Design accessible, high-contrast statistical dashboards for government leaders',
      'Generate choropleth thematic maps for district-level indicator tracking',
      'Adhere to National Data & Analytics Platform (NDAP) publishing standards',
    ],
    relevanceToGap: 'Transforms statistical tabulations into actionable executive insights.',
    expectedImprovement: 'Elevates Data Visualization from Level 2 to Level 3 verified status.',
    isDemoData: true,
    datasetNotice: 'Development Dataset',
    rating: 4.7,
    enrolledCount: 1680,
    url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Data+Visualization+Policy',
    mode: 'Online Self-Paced (iGOT)',
    phase: 'FOUNDATION',
  },

  // ==========================================
  // SOURCE 2: NSSTA / TPAC Residential Academies
  // ==========================================
  {
    id: 'cat-nssta-py-2026-01',
    title: 'Advanced Statistical Computing, Survey Automation & Large Microdata (Python/R)',
    source: 'NSSTA / TPAC',
    competency: 'Python',
    competencyLevel: 4,
    domain: 'Technical Competencies',
    difficulty: 'Advanced',
    duration: '3 Days (Residential)',
    durationCategory: 'LONG',
    prerequisites: 'Completion of iGOT Python foundational modules or 2+ years statistical service',
    targetRole: 'Assistant Director / Deputy Director (Statistics)',
    description: '3-Day intensive residential cohort at NSSTA Greater Noida campus. Hands-on laboratory training on processing 50GB+ PLFS and ASI raw microdata, parallel batch scripts, and Taylor-series variance linearisation.',
    learningObjectives: [
      'Build end-to-end automated survey validation and tabular output pipelines',
      'Optimize compute bottlenecks using Polars, Dask, and vectorised NumPy C-extensions',
      'Apply complex survey variance estimation and replication weights (Jackknife/BRR)',
      'Peer-review institutional codebase with senior Indian Statistical Service (ISS) faculty',
    ],
    relevanceToGap: 'Faculty-led practical immersion designed to accelerate Python application skills to Level 4 leadership mastery.',
    expectedImprovement: 'Qualifies officers for Level 4 Competency Passport certification and departmental lead roles.',
    isDemoData: true,
    datasetNotice: 'Development Dataset',
    rating: 4.95,
    enrolledCount: 28,
    url: 'https://www.mospi.gov.in/national-statistical-systems-training-academy-nssta',
    mode: 'Residential Academy (NSSTA Greater Noida)',
    phase: 'APPLICATION',
  },
  {
    id: 'cat-nssta-na-2026-02',
    title: 'Advanced National Accounting Matrix & Supply-Use Compilation Workshop',
    source: 'NSSTA / TPAC',
    competency: 'National Accounts (SNA 2008)',
    competencyLevel: 4,
    domain: 'Domain Competencies',
    difficulty: 'Advanced',
    duration: '5 Days (Residential)',
    durationCategory: 'LONG',
    prerequisites: 'Experience in macroeconomic data compilation or NAD division posting',
    targetRole: 'Deputy Director / Director (National Accounts)',
    description: 'Residential academy deep-dive with National Accounts Division (NAD) leadership and international macroeconomic experts on SUT reconciliation, deflators, and unorganized manufacturing estimation.',
    learningObjectives: [
      'Reconcile inter-industry commodity flows in Supply-Use frameworks',
      'Implement double deflation methodology across 83 manufacturing sectors',
      'Calibrate quarterly GVA estimates with high-frequency administrative signals (GST, IIP)',
    ],
    relevanceToGap: 'Hands-on matrix reconciliation under direct supervision of NAD chief compilers.',
    expectedImprovement: 'Elevates National Accounts Competency to verified Level 4 leadership tier.',
    isDemoData: true,
    datasetNotice: 'Development Dataset',
    rating: 4.9,
    enrolledCount: 22,
    url: 'https://www.mospi.gov.in/national-statistical-systems-training-academy-nssta',
    mode: 'Residential Academy (NSSTA Greater Noida)',
    phase: 'APPLICATION',
  },
  {
    id: 'cat-nssta-sm-2026-03',
    title: 'Masterclass on Sample Survey Multi-Stage Frame Design & CAPI Protocols',
    source: 'NSSTA / TPAC',
    competency: 'Survey Methodology',
    competencyLevel: 4,
    domain: 'Domain Competencies',
    difficulty: 'Advanced',
    duration: '4 Days (Residential)',
    durationCategory: 'LONG',
    prerequisites: 'SDRD or FOD operational experience',
    targetRole: 'Senior Statistical Officer / Assistant Director (SDRD)',
    description: 'Residential workshop focusing on probability proportional to size (PPS) sampling, CAPI real-time quality audits, multiplier adjustments, and non-response imputation in household surveys.',
    learningObjectives: [
      'Formulate sampling frames for rural/urban strata with boundary changes',
      'Configure automated CAPI skip logic and consistency checks on mobile devices',
      'Calculate multi-stage inflation multipliers and non-sampling error metrics',
    ],
    relevanceToGap: 'Provides practical masterclass training on official NSS survey cycle operations.',
    expectedImprovement: 'Elevates Survey Methodology to Level 4 verified master status.',
    isDemoData: true,
    datasetNotice: 'Development Dataset',
    rating: 4.88,
    enrolledCount: 30,
    url: 'https://www.mospi.gov.in/national-statistical-systems-training-academy-nssta',
    mode: 'Residential Academy (NSSTA Greater Noida)',
    phase: 'APPLICATION',
  },

  // ==========================================
  // SOURCE 3: NIPUN Practical Learning Sandboxes
  // ==========================================
  {
    id: 'cat-lab-py-301',
    title: 'PLFS Household Survey Microdata Cleaning & pandas Imputation Sandbox',
    source: 'NIPUN Practical Learning',
    competency: 'Python',
    competencyLevel: 3,
    domain: 'Technical Competencies',
    difficulty: 'Intermediate',
    duration: '45 mins',
    durationCategory: 'SHORT',
    prerequisites: 'None',
    targetRole: 'All Statistical Officers',
    description: 'Interactive in-browser Jupyter/Python simulation. Clean simulated 100,000-row Periodic Labour Force Survey (PLFS) microdata records, identify outlier earnings, and apply donor imputation.',
    learningObjectives: [
      'Write vectorized pandas filtering to isolate extreme outliers',
      'Apply group-level median imputation without introducing artificial variance',
      'Export verified tabulations formatted for official MoSPI annual release',
    ],
    relevanceToGap: 'Directly validates practical scripting competency on authentic survey data formats.',
    expectedImprovement: 'Generates empirical code artifact for Competency Passport Level 3 upgrade.',
    isDemoData: true,
    datasetNotice: 'Development Dataset',
    rating: 4.95,
    enrolledCount: 3120,
    url: '#',
    mode: 'Interactive In-Browser Simulation',
    phase: 'APPLICATION',
  },
  {
    id: 'cat-lab-na-302',
    title: 'Quarterly GVA Double-Deflation & SUT Balancing Simulation Lab',
    source: 'NIPUN Practical Learning',
    competency: 'National Accounts (SNA 2008)',
    competencyLevel: 3,
    domain: 'Domain Competencies',
    difficulty: 'Intermediate',
    duration: '40 mins',
    durationCategory: 'SHORT',
    prerequisites: 'Basic knowledge of CPI/WPI indices',
    targetRole: 'Statistical Officers in NAD / CSO',
    description: 'Interactive macroeconomic lab: deflate manufacturing gross output with WPI sub-indices, deflate intermediate inputs with weighted commodity baskets, and observe real GVA growth impacts.',
    learningObjectives: [
      'Compute separate output and input price deflators for 10 manufacturing sub-sectors',
      'Eliminate the distortion of single-deflation during commodity price spikes',
      'Balance supply-use discrepancies using automated RAS algorithm iterations',
    ],
    relevanceToGap: 'Hands-on practice resolving deflation biases in official GDP reporting.',
    expectedImprovement: 'Demonstrates practical mastery for Level 3/4 National Accounts verification.',
    isDemoData: true,
    datasetNotice: 'Development Dataset',
    rating: 4.85,
    enrolledCount: 1540,
    url: '#',
    mode: 'Interactive In-Browser Simulation',
    phase: 'APPLICATION',
  },
  {
    id: 'cat-lab-sm-303',
    title: 'NSSO Multiplier Weight Calibration & Estimation Sandbox',
    source: 'NIPUN Practical Learning',
    competency: 'Survey Methodology',
    competencyLevel: 3,
    domain: 'Domain Competencies',
    difficulty: 'Intermediate',
    duration: '35 mins',
    durationCategory: 'SHORT',
    prerequisites: 'Basic sampling formula knowledge',
    targetRole: 'Survey Field & Processing Officers',
    description: 'Hands-on calculation lab: compute design weights for first-stage units (villages/urban blocks), adjust for casualty units, and calculate weighted state-level poverty estimates.',
    learningObjectives: [
      'Calculate FSU and USU inclusion probabilities under PPS design',
      'Apply post-stratification adjustment factors to match census benchmarks',
      'Estimate standard errors and design effects (DEFF) on household consumption data',
    ],
    relevanceToGap: 'Reinforces exact mathematical weighting workflows used in NSO survey rounds.',
    expectedImprovement: 'Validates quantitative sampling precision for Level 3 Passport verification.',
    isDemoData: true,
    datasetNotice: 'Development Dataset',
    rating: 4.9,
    enrolledCount: 1890,
    url: '#',
    mode: 'Interactive In-Browser Simulation',
    phase: 'APPLICATION',
  },
];

export const CLIENT_RECOMMENDATIONS: UnifiedRecommendation[] = [
  {
    id: 'rec-python-01',
    competencyName: 'Python',
    currentLevel: 2,
    requiredLevel: 4,
    gapSize: 2,
    gapLabel: 'Application Gap: Level 2 → Level 4',
    reason: 'Current Level 2 syntax understanding is insufficient for Level 4 automated survey microdata processing and variance linearisation required in the target role.',
    explanation: {
      skillGap: 'Python L2 → L4',
      roleRelevance: 'Required for Deputy Director (Statistics)',
      prerequisite: 'Basic Python & Spreadsheet data cleaning',
      reason: 'Targets identified Python application gap by bridging syntax to survey pipelines.',
    },
    igotOption: {
      id: 'cat-igot-py-101',
      title: 'Python for Official Statistical Analysis & Data Processing',
      provider: 'iGOT Karmayogi / MoSPI',
      duration: '2h 30m',
      competency: 'Python',
      competencyLevel: 3,
      category: 'Technical Competencies',
      difficulty: 'Intermediate',
      relevanceScore: 96,
      recommendationReason: 'Addresses syntax comprehension and modular function design for survey processing pipelines.',
      rating: 4.8,
      enrolledCount: 1420,
      url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Python+Statistical+Analysis',
      isDemoData: true,
    },
    nsstaOption: {
      id: 'cat-nssta-py-2026-01',
      title: 'Advanced Statistical Computing, Survey Automation & Large Microdata (Python/R)',
      category: 'ISS Refresher Training',
      duration: '3 Days (Residential)',
      mode: 'In-Person (NSSTA Campus, Greater Noida)',
      targetCadre: 'Assistant Director / Deputy Director (Statistics)',
      competenciesCovered: ['Python', 'Large Microdata', 'Survey Automation'],
      upcomingBatchDate: '15-17 Sept 2026',
      eligibility: 'All Statistical Officers',
      tpacAligned: true,
      recommendationReason: 'Residential faculty-led deep dive at NSSTA Greater Noida campus for advanced statistical estimation.',
      isDemoData: true,
      location: 'NSSTA Campus, Greater Noida',
      dates: '15-17 Sept 2026',
      competency: 'Python',
      targetLevel: 4,
      seatsAvailable: 24,
      batchCode: 'NSSTA-2026-COHORT',
      description: 'Hands-on laboratory training on processing 50GB+ PLFS and ASI raw microdata, parallel batch scripts, and Taylor-series variance linearisation.',
    },
    nipunPracticeOption: {
      id: 'cat-lab-py-301',
      title: 'PLFS Household Survey Microdata Cleaning & pandas Imputation Sandbox',
      duration: '45 mins',
      scenario: 'Simulated 100,000-row Periodic Labour Force Survey records with outlier income reporting and missing industry codes.',
      description: 'Interactive in-browser Jupyter/Python simulation. Clean survey microdata and apply donor imputation.',
      type: 'INTERACTIVE_LAB',
    },
    matchedSources: {
      igot: true,
      nssta: true,
      nipun: true,
    },
  },
  {
    id: 'rec-dataviz-02',
    competencyName: 'Data Visualization',
    currentLevel: 2,
    requiredLevel: 3,
    gapSize: 1,
    gapLabel: 'Developing: Level 2 → Level 3',
    reason: 'Need automated interactive dashboarding skills to present survey findings to senior ministry policy makers without manual static plotting.',
    explanation: {
      skillGap: 'Data Visualization L2 → L3',
      roleRelevance: 'Required for Executive Policy Dissemination',
      prerequisite: 'Basic chart design and data summary skills',
      reason: 'Transforms statistical tabulations into actionable executive insights.',
    },
    igotOption: {
      id: 'cat-igot-dv-501',
      title: 'Official Statistical Visualizations & Dashboards for Policy Makers',
      provider: 'iGOT Karmayogi / MoSPI',
      duration: '2h 00m',
      competency: 'Data Visualization',
      competencyLevel: 3,
      category: 'Technical Competencies',
      difficulty: 'Intermediate',
      relevanceScore: 92,
      recommendationReason: 'Best practices for translating complex statistical tables into intuitive dashboards and thematic heatmaps.',
      rating: 4.7,
      enrolledCount: 1680,
      url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=Data+Visualization+Policy',
      isDemoData: true,
    },
    nsstaOption: {
      id: 'cat-nssta-py-2026-01',
      title: 'Advanced Statistical Computing & Visual Communication Workshop',
      category: 'ISS Refresher Training',
      duration: '3 Days',
      mode: 'In-Person (NSSTA Campus, Greater Noida)',
      targetCadre: 'Senior Statistical Officer / Assistant Director',
      competenciesCovered: ['Data Visualization', 'Executive Briefing', 'PowerBI'],
      upcomingBatchDate: '22-24 Sept 2026',
      eligibility: 'All Statistical Officers',
      tpacAligned: true,
      recommendationReason: 'Practical workshop on creating NDAP-compliant indicators and interactive maps.',
      isDemoData: true,
      location: 'NSSTA Campus, Greater Noida',
      dates: '22-24 Sept 2026',
      competency: 'Data Visualization',
      targetLevel: 3,
      seatsAvailable: 20,
      batchCode: 'NSSTA-VIZ-2026',
      description: 'Hands-on training creating district choropleth maps and interactive visual dashboards for policy dissemination.',
    },
    nipunPracticeOption: {
      id: 'cat-lab-py-301',
      title: 'MoSPI Thematic Map & Policy Indicator Dashboard Sandbox',
      duration: '40 mins',
      scenario: 'Multi-district socio-economic indicators across 750 districts requiring thematic mapping.',
      description: 'Build responsive heatmaps and interactive drilldown charts adhering to NDAP open standards.',
      type: 'SIMULATION',
    },
    matchedSources: {
      igot: true,
      nssta: true,
      nipun: true,
    },
  },
  {
    id: 'rec-privacy-03',
    competencyName: 'Data Privacy & DPDP Act',
    currentLevel: 2,
    requiredLevel: 3,
    gapSize: 1,
    gapLabel: 'Knowledge Gap: Level 2 → Level 3',
    reason: 'Statutory compliance mandate under DPDP Act 2023 for handling anonymized public microdata dissemination.',
    explanation: {
      skillGap: 'Data Privacy & DPDP Act L2 → L3',
      roleRelevance: 'Statutory Compliance Mandate',
      prerequisite: 'None',
      reason: 'Critical compliance requirement for microdata dissemination and public research access.',
    },
    igotOption: {
      id: 'cat-igot-dp-401',
      title: 'Digital Personal Data Protection (DPDP) Act 2023 for Official Statisticians',
      provider: 'iGOT Karmayogi / Ministry of Law',
      duration: '1h 30m',
      competency: 'Data Privacy & DPDP Act',
      competencyLevel: 3,
      category: 'Digital Governance',
      difficulty: 'Intermediate',
      relevanceScore: 98,
      recommendationReason: 'Statutory obligations of Data Fiduciaries and anonymization protocols under DPDP Act 2023.',
      rating: 4.9,
      enrolledCount: 3450,
      url: 'https://igotkarmayogi.gov.in/app/search?primaryCategory=Course&q=DPDP+Act+2023+Government',
      isDemoData: true,
    },
    nsstaOption: {
      id: 'cat-nssta-sm-2026-03',
      title: 'Legal Compliance, Statistical Confidentiality & SDC Protocols',
      category: 'ISS Refresher Training',
      duration: '2 Days',
      mode: 'In-Person (NSSTA Campus, Greater Noida)',
      targetCadre: 'All Cadre Officers',
      competenciesCovered: ['Data Privacy & DPDP Act', 'Statistical Disclosure Control'],
      upcomingBatchDate: '01-02 Oct 2026',
      eligibility: 'All Statistical Officers',
      tpacAligned: true,
      recommendationReason: 'Executive seminar on statistical disclosure control and legal data governance.',
      isDemoData: true,
      location: 'NSSTA Campus, Greater Noida',
      dates: '01-02 Oct 2026',
      competency: 'Data Privacy & DPDP Act',
      targetLevel: 3,
      seatsAvailable: 35,
      batchCode: 'NSSTA-DPDP-2026',
      description: 'In-depth review of Data Fiduciary rules, consent management, and microdata release governance.',
    },
    nipunPracticeOption: {
      id: 'cat-lab-sm-303',
      title: 'Microdata Anonymization & k-Anonymity Verification Sandbox',
      duration: '35 mins',
      scenario: 'Household survey sample with quasi-identifiers requiring top-coding and cell perturbation.',
      description: 'Apply statistical disclosure control techniques to generate compliant public use files (PUF).',
      type: 'SIMULATION',
    },
    matchedSources: {
      igot: true,
      nssta: true,
      nipun: true,
    },
  },
];
