import type { NSSTAProgramme } from '../../../src/types';

export const MOCK_NSSTA_PROGRAMMES: NSSTAProgramme[] = [
  {
    id: 'nssta-prog-301',
    title: 'Advanced Statistical Computing, Big Data Analytics & Python in Official Statistics',
    category: 'ISS Refresher Training',
    duration: '3 Days (Residential)',
    mode: 'In-Person (NSSTA Campus, Greater Noida)',
    targetCadre: 'Senior Statistical Officers (SSO), Junior Statistical Officers (JSO), ISS Officers',
    competenciesCovered: ['Python', 'Data Visualization', 'Statistical Analysis', 'Big Data Analytics'],
    upcomingBatchDate: '15-17 Sept 2026',
    eligibility: 'Serving SSS / ISS officers with minimum 2 years field or data processing experience',
    tpacAligned: true,
    recommendationReason: 'Directly addresses practical application gap in Python and survey microdata processing.',
    isDemoData: true,
  },
  {
    id: 'nssta-prog-102',
    title: 'Modern Survey Sampling Techniques, Frame Construction & Estimation Procedures',
    category: 'Demand Based Training',
    duration: '5 Days',
    mode: 'Hybrid',
    targetCadre: 'Survey Officers, Statistical Investigators, Field Operations Division (FOD)',
    competenciesCovered: ['Sampling', 'Survey Design', 'Official Statistics Methodology'],
    upcomingBatchDate: '22-26 Sept 2026',
    eligibility: 'Officers involved in NSS, Periodic Labour Force Survey (PLFS), and Annual Survey of Industries (ASI)',
    tpacAligned: true,
    recommendationReason: 'Recommended by TPAC to strengthen probability sampling and complex weight estimations.',
    isDemoData: true,
  },
  {
    id: 'nssta-prog-204',
    title: 'National Accounts Statistics: Supply-Use Tables & Quarterly GDP Compilation',
    category: 'ISS Refresher Training',
    duration: '4 Days',
    mode: 'In-Person (NSSTA Campus, Greater Noida)',
    targetCadre: 'National Accounts Division (NAD) Officers & State DES Officials',
    competenciesCovered: ['National Accounts', 'Data Quality Frameworks', 'Macroeconomic Indicators'],
    upcomingBatchDate: '06-09 Oct 2026',
    eligibility: 'Officials handling state domestic product (GSDP) or national accounts aggregates',
    tpacAligned: true,
    recommendationReason: 'Comprehensive hands-on training on SNA 2008 guidelines and inter-industry linkages.',
    isDemoData: true,
  },
  {
    id: 'nssta-prog-401',
    title: 'Executive Workshop on AI/ML Applications and Automated Data Validation in Governance',
    category: 'TPAC Recommended',
    duration: '2 Days',
    mode: 'Virtual',
    targetCadre: 'Deputy Directors, Joint Directors, Senior Statistical Officers',
    competenciesCovered: ['AI / ML', 'Automation', 'Digital Governance'],
    upcomingBatchDate: '19-20 Oct 2026',
    eligibility: 'All officers seeking foundational operational exposure to generative and predictive AI in statistics',
    tpacAligned: true,
    recommendationReason: 'Emerging skill mandate to modernize statistical release and automated validation engines.',
    isDemoData: true,
  },
  {
    id: 'nssta-prog-501',
    title: 'Induction & Statistical Capacity Building for State / UT DES Personnel',
    category: 'State / UT Training',
    duration: '2 Weeks',
    mode: 'In-Person (NSSTA Campus, Greater Noida)',
    targetCadre: 'State Statistical Service Personnel and UT Planning Officers',
    competenciesCovered: ['Price Statistics', 'Agricultural Statistics', 'SDG Indicators', 'Survey Design'],
    upcomingBatchDate: '02-13 Nov 2026',
    eligibility: 'Nominated personnel from State Directorates of Economics and Statistics',
    tpacAligned: true,
    recommendationReason: 'Core institutional harmonization of state-level statistical indicators with national standards.',
    isDemoData: true,
  },
];
